dist: xenial
services:
  - xvfb
addons:
  chrome: stable
language: node_js
sudo: required
notifications:
  email: false
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
after_success:
  - npm run build
  - cp .git dist/ngx-electron/ -r
  - cp README.md dist/ngx-electron/
  - cd dist/ngx-electron/
  - npm install
  - npm run semantic-release
deploy:
  provider: npm
  email: "cheongnanfeng@gmail.com"
  api_key: $NPM_TOKEN
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
